; PlatformIO Project Configuration File — NTC Probe Sensor
; No external sensor libraries needed; temperature is calculated from raw ADC.

[env:xiao_esp32c6_sensor_ntc]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board_build.variant = esp32c6
board = seeed_xiao_esp32c6
framework = arduino
build_flags =
	-Os
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
