[env:xiao_esp32c6_sensor]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board_build.variant = esp32c6
board     = seeed_xiao_esp32c6
framework = arduino

build_flags =
    -Os                          ; Smallest Code
    -DARDUINO_USB_CDC_ON_BOOT=1  ; Enable USB-CDC Serial from first boot byte

lib_deps =
    sensirion/Sensirion I2C SHT4x@^1.0.0
