[env:xiao_esp32c6_hub]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board     = seeed_xiao_esp32c6
framework = arduino

; NimBLE + WebServer won't fit in the default 1.25 MB app partition
board_build.variant    = esp32c6
board_build.partitions = huge_app.csv

build_flags = -Os   ; Smallest Code

lib_deps =
    h2zero/NimBLE-Arduino@^2.0.0
    knolleary/PubSubClient@^2.8
