#!/usr/bin/env node
/*
 * Firmware signing for Temp-sensors OTA.
 *
 * The hub downloads images over a TLS connection it does not authenticate
 * (WiFiClientSecure.setInsecure()), so the transport proves nothing. The ECDSA
 * signature is the only thing standing between the fleet and an attacker-
 * supplied image — verified on-device before the new slot is made bootable.
 *
 * The private key must never be committed or copied to the droplet. Keep it on
 * a dev machine (or offline media); the droplet only ever sees signatures.
 *
 * Usage:
 *   node sign.js keygen                 — create a keypair, print the C array
 *   node sign.js pubkey <key.pem>       — re-print the C array for an existing key
 *   node sign.js sign <key.pem> <fw.bin>— print sha256 + base64 signature
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const CURVE = 'prime256v1'; // NIST P-256 — MBEDTLS_ECP_DP_SECP256R1 on the hub

function die(msg) {
  console.error(`error: ${msg}`);
  process.exit(1);
}

// Emit an SPKI DER public key as a C array for embedding in hub firmware.
// mbedtls_pk_parse_public_key() consumes exactly this format.
function toCArray(der) {
  const lines = [];
  for (let i = 0; i < der.length; i += 12) {
    const row = [...der.subarray(i, i + 12)]
      .map((b) => `0x${b.toString(16).padStart(2, '0').toUpperCase()}`)
      .join(', ');
    lines.push(`  ${row},`);
  }
  return (
    `// ECDSA P-256 public key (SPKI DER), ${der.length} bytes.\n` +
    `// Generated by tools/firmware-signing/sign.js — replace only when rotating keys,\n` +
    `// and remember that a hub can only be updated by a key it already trusts.\n` +
    `static const uint8_t FW_PUBLIC_KEY[] = {\n${lines.join('\n')}\n};`
  );
}

function keygen() {
  const outPath = path.resolve('fw-signing-key.pem');
  if (fs.existsSync(outPath)) {
    die(`${outPath} already exists — refusing to overwrite an existing signing key`);
  }

  const { privateKey, publicKey } = crypto.generateKeyPairSync('ec', {
    namedCurve: CURVE,
  });

  fs.writeFileSync(
    outPath,
    privateKey.export({ type: 'pkcs8', format: 'pem' }),
    { mode: 0o600 }
  );

  console.log(`Private key written to ${outPath}`);
  console.log('KEEP THIS FILE OFF GIT AND OFF THE DROPLET.\n');
  console.log(toCArray(publicKey.export({ type: 'spki', format: 'der' })));
}

function pubkey(keyPath) {
  const privateKey = crypto.createPrivateKey(fs.readFileSync(keyPath));
  const publicKey = crypto.createPublicKey(privateKey);
  console.log(toCArray(publicKey.export({ type: 'spki', format: 'der' })));
}

function sign(keyPath, binPath) {
  const privateKey = crypto.createPrivateKey(fs.readFileSync(keyPath));
  const image = fs.readFileSync(binPath);

  const sha256 = crypto.createHash('sha256').update(image).digest('hex');
  const signature = crypto.createSign('SHA256').update(image).sign(privateKey);

  console.log(`file:      ${binPath}`);
  console.log(`size:      ${image.length}`);
  console.log(`sha256:    ${sha256}`);
  console.log(`signature: ${signature.toString('base64')}`);
}

const [cmd, ...args] = process.argv.slice(2);
switch (cmd) {
  case 'keygen':
    keygen();
    break;
  case 'pubkey':
    if (!args[0]) die('usage: sign.js pubkey <key.pem>');
    pubkey(args[0]);
    break;
  case 'sign':
    if (args.length < 2) die('usage: sign.js sign <key.pem> <firmware.bin>');
    sign(args[0], args[1]);
    break;
  default:
    die('usage: sign.js keygen | pubkey <key.pem> | sign <key.pem> <fw.bin>');
}
